---
- name: Playbook for testing firewall related roles
  hosts: all

  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

  roles:
    - role: "../roles/facts"
    # - role: "../roles/ufw"
    #   vars:
    #     ufw_lockdown: true
    #     ufw_open_ports:
    #       - 8080
    #       - 443
    #     ufw_apps:
    #       - "OpenSSH"
    #     ufw_source_ips:
    #       - 192.168.121.63
    #       - 1.1.1.1
    - role: "../roles/firewalld"
      vars:
        firewalld_lockdown: true
        # firewalld_source_ips:
        #   - 192.168.122.12
        #   - 8.8.8.8
        # firewalld_services:
        #   - https
        firewalld_open_ports:
          - 8000
          - 80
          - 53
    # - role: "../roles/iptables"
    #   vars:
    #     iptables_lockdown: true
    #     iptables_source_ips:
    #       - "192.168.121.63"
    #     # iptables_open_ports:
    #     #   - 80
  