- name: list installed applications in network
  hosts: all
  become: true

  tasks:
    - name: check all installed packages on apt
      ansible.builtin.shell:
        cmd: sudo apt list --installed

    - name: check all installed packages on dnf
      ansible.builtin.shell:  
        cmd: sudo dnf repoquery --userinstalled

    - name: check all installed packages on nix
      ansible.builtin.shell:  
        cmd: nix-store --query --requisites /run/current-system

    - name: check all installed packages on Windows
      ansible.builtin.shell:
        cmd: Get-Package

    - name: create local log
      ansible.builtin.file:
        path: ~/output.txt
        owner: root
        group: root
        mode: '0644'
      delegate_to: localhost

    - name: output list into local file
      ansible.builtin.copy:
        content: "{{command_output.stdout}}"
        dest: ~/output.txt
      delegate_to: localhost