---
- name: Playbook aimed at debian, to test shuffling the users role
  hosts: all
  roles:
    - role: "../roles/facts"
    # - role: "../roles/backup"
    #   vars:
    #     backup_version: "fresh"
    #     backup_directories:
    #       - /etc/systemd/
        # backup_restore:
        #   - /etc/systemd/
    - role: "../roles/users"
      vars:
        users_admins: ["vagrant", "root"]
        users_passwords_shuffle: true
        users_admin_password: "testing!"

  # tasks:
  #   - name: Get local users
  #     become: true
  #     ansible.builtin.set_fact:
  #       users_list: "{{ lookup('file', '/etc/passwd') | split('\n') | map('regex_replace', '(.*?):.*', '\\1:') }}"
  #   - name: Get human users
  #     become: true
  #     ansible.builtin.getent:
  #       database: passwd
  #     register: passwd
  #   - name: Print local users
  #     ansible.builtin.debug:
  #       var: users_list
  #   - name: Print getent
  #     ansible.builtin.debug:
  #       var: passwd
    
